# Generated by Django 5.2 on 2025-04-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_alter_todoitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='title',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='text',
            field=models.CharField(default='No title', max_length=255),
        ),
    ]
